@startuml
title
  Tutorial 6 - add_person_to_lookup-directory sequence
end title
actor main
entity nameLookupDirectory as gsma
control "metaphone Library" as meta


autonumber 10 10 "[000]"
main -> gsma: __init__()

main -> gsma: add_person_to_lookup_directory(person_id,name_tuple)
activate gsma
    gsma -> gsma: generate_combinations(name_tuple): tuples
    gsma -> gsma: add_combinations_to_directory(tuples, person_id)
    activate gsma
        loop forEach tuple in tuples
            gsma -> gsma: generate_normalized_name(tuple): norm_name
            gsma -> meta: doublemetaphone(norm_name); db_tuple
            gsma -> gsma: addToLookupDictionaryIfNecessary(db_tuple, person_id)

        end
                 gsma --> main
    deactivate gsma
deactivate gsma







@enduml